import os
import pytest

from pydantic import BaseModel
from bootstrap.container import VerzaContainer
from contracts.schemas.context import AIContext, ExecutionContext
from contracts.schemas.world import Evidence, WorldState
from contracts.schemas.prompt import PromptAsset
from core.workflow.interpretation import InterpretationEngine
from providers.cognitive.gemini.provider import GeminiVLMProvider

# Ensure that we skip if no real API key is present
pytestmark = pytest.mark.skipif(
    not os.getenv("GEMINI_API_KEY"),
    reason="ENVIRONMENT DEPENDENCY FAILURE: GEMINI_API_KEY is missing."
)


@pytest.fixture
def interpretation_engine():
    container = VerzaContainer()
    return container.interpretation_engine()


@pytest.mark.real_api
def test_real_gemini_interpretation(interpretation_engine: InterpretationEngine):
    """
    M3.1: Real Gemini VLM Interpretation (E2E).
    Verifies that the InterpretationEngine can hit the real Gemini API
    and return structured Pydantic WorldStateDelta objects without hallucinating formatting.
    """
    # 1. Create a dummy initial state
    initial_context = AIContext(media_id="test-media-001")
    
    # Normally Evidence comes from the Engine, but the Mock Engine just hardcodes it. 
    # Let's run the InterpretationEngine which uses our actual VLM Provider.
    
    # We override the engine's internal VLM provider to be explicit about it running real API.
    # It's already configured to use gemini if VERZA_VLM_MODEL is gemini, but let's verify.
    assert isinstance(interpretation_engine.vlm_provider, GeminiVLMProvider), \
        "InterpretationEngine must be configured to use GeminiVLMProvider for this test."
    
    # Execute the engine
    final_context = interpretation_engine.execute(initial_context)
    
    # Verify that the journal contains Deltas
    journal_history = interpretation_engine.journal.get_history()
    assert len(journal_history) > 0, "Expected InterpretationEngine to produce at least one delta."
    
    # Verify that the world state has been mutated by the deltas
    # (E.g. visual.scenes should now contain the scene interpretation)
    assert len(final_context.world.visual.scenes) > 0, "Expected visual scenes to be populated by SceneInterpreter."
    scene = final_context.world.visual.scenes[0]
    
    # It should have a real summary generated by Gemini.
    assert isinstance(scene.get("summary"), str)
    assert len(scene.get("summary")) > 5, "Expected a meaningful summary from the VLM."
